server:
  port: 9090

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold:
        2MB
      max-file-size:
        5MB
      max-request-size:
        10MB

application:
  bucket:
    name: upload-download-example

cloud:
  aws:
    credentials:
      access-key: ${aws_access_key}
      secret-key: ${aws_secret_key}
    region:
      static: eu-central-1
    stack:
      auto: false