server:
  port: 9090

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold:
        2MB
      max-file-size:
        5MB
      max-request-size:
        10MB

application:
  bucket:
    name: upload-download-example

cloud:
  aws:
    credentials:
      access-key: AKIA2CB7BWRH5X2CXF4C
      secret-key: oryeGkMyDiG2+5BCY5mPqtIgYgftddeqLNJPcPys
    region:
      static: eu-central-1
    stack:
      auto: false